parameters:
    database_name: symfony_test
    database_user: symfony_test
    database_password: symfony_test
    'qimnet.update_tracker.entity_name': 'Qimnet\UpdateTrackerTestBundle\Entity\UpdateTrackerTest'
